#! /bin/sh
 
RETVAL=0
PROG="git-daemon"
GIT_DAEMON="/opt/local/bin/ruby /opt/local/gitorious/script/git-daemon -d"
LOCK_FILE=/opt/local/var/run/git-daemon
PID_FILE=/opt/local/gitorious/log/git-daemon.pid
SU=/usr/bin/su
 
do_check_pid() {
  if [ -f $PID_FILE ]; then
    PID=`cat $PID_FILE`
    RUNNING=`ps -p $PID | wc -l`
  else
    PID=0
    RUNNING=0
  fi
}
 
start()
{
  do_check_pid
  if [ $RUNNING != 2 ] ; then
    echo -n "Starting $PROG: "
    $SU - git -c "$GIT_DAEMON"
    sleep 5
    if [ -f $PID_FILE ] ; then
      echo "success"
      RETVAL=0
    else
      echo "failure"
      RETVAL=1
    fi
  else
    echo -n "$PROG already running"
    RETVAL=1
  fi
  [ "$RETVAL" = 0 ] && touch $LOCK_FILE
  echo
}
 
stop()
{
  do_check_pid
  echo -n "Stopping $PROG: "
  if [ $RUNNING != 2 ] ; then
    echo -n "Stopping $PROG"
  else
    PROGPID=`cat $PID_FILE`
    kill -TERM $PROGPID
  fi
  RETVAL=0
  [ "$RETVAL" = 0 ] && rm -f $LOCK_FILE && rm -f $PID_FILE
  echo
}
 
case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart)
    stop
    start
    ;;
  *)
    echo $"Usage: $0 {start|stop|restart}"
    RETVAL=1
esac
exit $RETVAL
